 CREATE TABLE "TM_LZ"."LT_SRC_PROTEIN_DISPLAY_MAPPING" 
   	(	"CATEGORY_CD" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
		"DISPLAY_VALUE" VARCHAR2(100 BYTE), 
		"DISPLAY_LABEL" VARCHAR2(200 BYTE), 
		"DISPLAY_UNIT" VARCHAR2(20 BYTE)
   	)
        
        create or replace synonym tm_cz.LT_SRC_PROTEIN_DISPLAY_MAPPING for "TM_LZ"."LT_SRC_PROTEIN_DISPLAY_MAPPING" ;
	grant select, insert, update, delete on  "TM_LZ"."LT_SRC_PROTEIN_DISPLAY_MAPPING" to tm_cz;